### ISSUE TITLE
Missing mdi-account-convert-outline icon

### ISSUE THREAD

**Issue by sawich** [robcresswell/vue-material-design-icons#114]
![изображение](https://user-images.githubusercontent.com/10461884/74896927-280b7880-539e-11ea-9502-8f0438befcf7.png)

**Comment by AlbertMarashi** [comment]
Missing AccountHardHat too

**Comment by robcresswell** [comment]
Should hopefully be fixed by https://github.com/robcresswell/vue-material-design-icons/pull/145, explanation is in the PR
