### ISSUE TITLE
How to use it as class name?

### ISSUE THREAD

**Issue by paulocoutinhox** [robcresswell/vue-material-design-icons#12]
Hi,

How i can use material design icons to use as class name, like:
```
mdi mdi-delete
```

Can anyone help me?

Thanks.

**Comment by paulocoutinhox** [comment]
Hi,

I solved it using this package (@mdi/font) and importing it on main.js:

```
import '@mdi/font/css/materialdesignicons.css'
```

Thanks.

**Comment by robcresswell** [comment]
@prsolucoes Yeah, this package exists so you don't need to use icon fonts (some browsers block them, they don't scale well, you end up importing all at once)

The idea here is to import SVG icons, one by one. Keeps bundle size small.
