### ISSUE TITLE
Missing Cogs icons

### ISSUE THREAD

**Issue by reefki** [robcresswell/vue-material-design-icons#150]
I noticed there are no cogs icons are found in the package, I mean some or maybe all of the icons that have `cog` in their name for example:

```
import Cog from "vue-material-design-icons/Cog";
import CogOutline from "vue-material-design-icons/CogOutline";
import AccountCog from "vue-material-design-icons/AccountCog";
```

**Comment by timtimmahh** [comment]
Try adding the `.vue` extension at the end of the names:

```
import Cog from "vue-material-design-icons/Cog.vue";
import CogOutline from "vue-material-design-icons/CogOutline.vue";
import AccountCog from "vue-material-design-icons/AccountCog.vue";
```

**Comment by reefki** [comment]
@timtimmahh thanks, it works! But I think it would be much better in terms of consistency if it could work without the `.vue` extension too as other icons.

**Comment by robcresswell** [comment]
@reefki I think this is a build issue on your side; there's nothing about those icons thats different. I don't even think I could try and make that inconsistent if I wanted to.

**Comment by robcresswell** [comment]
Closing, as there has been no response in almost a month.
