### ISSUE TITLE
Dynamic usage

### ISSUE THREAD

**Issue by shaljam** [robcresswell/vue-material-design-icons#171]
I would like to render icons dynamically. I tried `v-html` but it won't work because the icons are `vue components` and not simple HTML. I think something like the following would be great.
```
<icon icon="menu" />
```

Something like `bootsrap-vue`'s [implementation](https://bootstrap-vue.org/docs/icons#icon-components) would be great. Note that they require the individual icon to be imported for this method to work.

**Comment by robcresswell** [comment]
I'm not sure I follow. Can you not use `v-if` to conditionally render whatever you want? Or a mapping of some sort.

Roughly, something like

```js
const icons = {
  menu: MenuIcon,
};
```

```vue
<keep-alive>
  <component v-bind:is="icons['menu']"></component>
</keep-alive>
```

Note the above is pseudocode; I don't do frontend development anymore, so I can't recall what the exact syntax would look like.

See also https://vuejs.org/v2/guide/components-dynamic-async.html

**Comment by robcresswell** [comment]
Closing, as there has been no response for nearly 3 months.
