### ISSUE TITLE
The MoveToInboxIcon hasn't been found

### ISSUE THREAD

**Issue by corvus-007** [robcresswell/vue-material-design-icons#190]
This icon look like that https://material.io/resources/icons/?search=inbox&icon=move_to_inbox&style=baseline

**Comment by robcresswell** [comment]
:disappointed: 

The very first line of the README points you to the source for these icons: https://github.com/Templarian/MaterialDesign

They can be browsed at http://materialdesignicons.com/

It looks like the icon you want is `InboxArrowDown`
