### ISSUE TITLE
Missing featured_play_list

### ISSUE THREAD

**Issue by Peter-Barrett** [robcresswell/vue-material-design-icons#224]
Looks like the icon featured_play_list is not available, it's the only icon I really need!

**Comment by robcresswell** [comment]
Can you link me to the icon on http://materialdesignicons.com/ please? I don't know which icon you are referring to.

**Comment by Peter-Barrett** [comment]
ah, I was looking at the other material design website. https://material.io/resources/icons/?icon=featured_play_list&style=baseline

I've since just imported it normally. Thanks
