### ISSUE TITLE
Vue3 - multiple compiler errors

### ISSUE THREAD

**Issue by elgorro** [robcresswell/vue-material-design-icons#273]
`"VueCompilerError: <template functional> is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal <template> instead."`

1. ArrowRight.vue
2. ChevronLeft.vue
3. ChevronRight.vue
4. Close.vue
5. DotsHorizontal.vue
6. Menu.vue
7. MenuDown.vue
8. Pause.vue
9. Pencil.vue
10. Play.vue
11. Undo.vue

**Comment by robcresswell** [comment]
See https://github.com/robcresswell/vue-material-design-icons/issues/230

Use `5.0.0`

**Comment by elgorro** [comment]
Sorry for confusion - I got this with `5.0.0`!

**Comment by robcresswell** [comment]
Oh! 🤔  I will investigate

**Comment by robcresswell** [comment]
@elgorro I don't think you did? See https://unpkg.com/browse/vue-material-design-icons@5.0.0/ArrowRight.vue

There's no `functional` in there. You may have updated your manifest and forgot to run install?

**Comment by elgorro** [comment]
You're right - something was maybe cached in my IDE! Now it shows the correct error in another dep, which is still using Vue2 respectivly `4.*`.
