### ISSUE TITLE
Can't import thin icon

### ISSUE THREAD

**Issue by RSurya99** [robcresswell/vue-material-design-icons#275]
Hello, I got an error that telling the icon is not found when I use thin material design icon, does this package not use the latest version of the material design icon?
![errorThinIcon](https://user-images.githubusercontent.com/73375663/150662679-877bae44-22a9-4d95-a1db-dc651fb2a8b1.png)

**Comment by robcresswell** [comment]
https://unpkg.com/vue-material-design-icons/ has all the latest icons. I don't pick the names, just mirror them from MDI and package them up as vue icons

**Comment by RSurya99** [comment]
> https://unpkg.com/vue-material-design-icons/ has all the latest icons. I don't pick the names, just mirror them from MDI and package them up as vue icons

I've checked it and see that the CDN doesn't have some icons like ArrowUpThin Icons, I don't know why but that's also a problem, the only solution is to change the icon to something else

![Material-Design-Icons](https://user-images.githubusercontent.com/73375663/157278084-d2188beb-e883-4ba0-972d-c94004203b71.png)

![Material-Design-Icons(2)](https://user-images.githubusercontent.com/73375663/157278833-d5c710b6-fa5a-4056-a95b-0dcf0a66d7b9.png)

**Comment by kaiserkiwi** [comment]
Multiple folder icons are missing too. For example FolderCancelIcon. Can we expect an update soon?

**Comment by robcresswell** [comment]
I've updated the lib, should have all the icons now
