### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by DamianGlowala** [robcresswell/vue-material-design-icons#278]
The `bell-cog` and `bell-cog-outline` icons appear to be missing (amongst many others).

@robcresswell, would you be able to update the `@mdi/js` dependency to the newest version (`6.7.96` as of today) and release a new version of the package? That would be very much appreciated.

**Comment by DamianGlowala** [comment]
@robcresswell, any updates on this one?

**Comment by DamianGlowala** [comment]
To anyone who comes across missing icons: there is a better alternative out there. I recommend migrating to [https://github.com/antfu/unplugin-icons](https://github.com/antfu/unplugin-icons).

**Comment by robcresswell** [comment]
I've released a new version of the lib, for those who want to keep using it
