### ISSUE TITLE
Missing icons?

### ISSUE THREAD

**Issue by christianlupus** [robcresswell/vue-material-design-icons#287]
Hello,

maybe I miss something relevant but I was not able to find the `TriangleDown` icon. In the https://materialdesignicons.com/ this exists as a 180 degree rotated version but I cannot find it in this repo.

Do I miss a trick to rotate it or was it simply overlooked? I have not checked for other missing icons.

Thanks

**Comment by robcresswell** [comment]
Hey @christianlupus! I think you might be looking for `TriangleSmallDown`? I can't find a `TriangleDown` icon.

https://unpkg.com/browse/vue-material-design-icons@5.2.0/TriangleSmallDown.vue

**Comment by christianlupus** [comment]
I am a bit surprised. You are right, the triangle showing downwards is not present. I am absolute positive that it was shown in there list of icons. Strange, either it was removed (unlikely) or i am getting old 🫣. Sorry for the noise.

PS: yes i found the small versions and used them. No clue what was happening just then.

**Comment by robcresswell** [comment]
@christianlupus No worries! Everyone has those days. Sorry for my slow response 😅
