### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by Jogai** [robcresswell/vue-material-design-icons#288]
This is probably the most annoying issue an open source maintainer could get, so my apologies for my question. What's the status of the project? Several issues and pr's are not picked up it seems, so it looks like the project is being abandoned.

**Comment by robcresswell** [comment]
Its not really "abandoned", but there isn't much to do beyond occasionally merge new icons. The open PRs / issues are not really big.

**Comment by robcresswell** [comment]
I've done some project cleanup, hopefully that helps you feel more comfortable about using it 😇

**Comment by Jogai** [comment]
Thanks, its just that I don't know what to do with a PR like this: https://github.com/vuejs/awesome-vue/pull/4008

**Comment by robcresswell** [comment]
I don't mind, I'm not precious about it. That person could've just put in a PR to this repo? I might have missed something, but I don't think they attempted to open an issue or PR here

**Comment by robcresswell** [comment]
I left a comment on the linked PR. Sorry for the trouble!

**Comment by vivek1996** [comment]
Hi @robcresswell, 
I thought this project was abandoned since there were a lot of PR & issues where pending.  So created a fork & published a new package. 
Closed the [PR](https://github.com/vuejs/awesome-vue/pull/4008). 
Thanks for the library!

**Comment by Jogai** [comment]
Great work guys!
