### ISSUE TITLE
Support import from top-level package

### ISSUE THREAD

**Issue by last-partizan** [robcresswell/vue-material-design-icons#44]
It would be nice to have ablity to import icons just from package, like this:

```
import {
  IconDoneky,
  IconMore,
} from "icons"
```

Right now i created simple python script for generating icons.js with lines like this
```
export { default as IconDonkey } from 'vue-material-design-icons/Donkey.vue'
export { default as IconMore } from 'vue-material-design-icons/More.vue'
```

Probably you can add something similar to build process, to create index.js.

**Comment by robcresswell** [comment]
See https://github.com/robcresswell/vue-material-design-icons/pull/104
