### ISSUE TITLE
v4 - @click events seem to be broken

### ISSUE THREAD

**Issue by Illyism** [robcresswell/vue-material-design-icons#49]
I've created unit tests to demonstrate the example.

- Working unit test in v3.4.0: https://github.com/robcresswell/vue-material-design-icons/pull/48
- The same unit test fails in v4.0.0: https://github.com/robcresswell/vue-material-design-icons/pull/47

For a real-life project, see https://github.com/Illyism/musicplayer/pull/79
- v3.4.0 https://musicplayer-io.netlify.com/
- v4.0.0 https://deploy-preview-79--musicplayer-io.netlify.com
- Eg The prev / play / next icons no longer accept @click events
- Used in this wage https://github.com/Illyism/musicplayer/blob/master/src/modules/player/VideoOverlay.vue#L69

![image](https://user-images.githubusercontent.com/304283/64566884-47b26580-d357-11e9-8319-068dc69351f5.png)

**Comment by robcresswell** [comment]
Gah, thanks for the report @Illyism. Are you okay to use the previous tag for now until I can get this fixed? May be a couple of days due to work.

**Comment by Illyism** [comment]
Of course, no rush! I tried looking into it myself but I couldn't get it to work for some reason. Only a non functional template seemed to work.
