### ISSUE TITLE
Switching to functional component broke my entire code base

### ISSUE THREAD

**Issue by Akumzy** [robcresswell/vue-material-design-icons#61]
Thank you for the amazing package though I thought this package was previously on GitLab.

Anyway I updated my entire dependencies `vue-material-design-icons` being on of them which broke my entire app because `v-on:click.native` that was working previously weirdly stopped working and after debugging I found out it was caused by the package using Functional component now.

I have corrected my bugs but I just want to make it known here too because I believe it should be labeled as breaking changes in the future.

Thank you for the amazing work once more.

**Comment by robcresswell** [comment]
@Akumzy This was labelled as a breaking change. See https://github.com/robcresswell/vue-material-design-icons/releases/tag/4.0.0

**Comment by Akumzy** [comment]
> I thought this package was previously on GitLab?

I didn't see that.

**Comment by robcresswell** [comment]
:smiley:
