### ISSUE TITLE
Classes and ids are not being applied

### ISSUE THREAD

**Issue by Mintonne** [robcresswell/vue-material-design-icons#63]
Hey,

From `v4.0.0`, classes and ids do not show up in the page markup.

### v3.4.0

![image](https://user-images.githubusercontent.com/39894801/66865774-a09d9b00-efa0-11e9-869e-be35d25e18e6.png)

### v4.0.0

![image](https://user-images.githubusercontent.com/39894801/66865795-aa270300-efa0-11e9-93a3-893368ee2d9b.png)

Reproduction - https://codesandbox.io/s/vue-template-qx0u9

**Comment by robcresswell** [comment]
:scream: Holy smokes, that's bad. I'll look into this ASAP; I think that'll be tomorrow evening

**Comment by robcresswell** [comment]
Hey @Mintonne did the commit tagged above fix this for you?

**Comment by Mintonne** [comment]
Everything seems to be working as expected.

**Comment by robcresswell** [comment]
Great. Thanks again for the issue, sorry it took me a while to get to.
