### ISSUE TITLE
styles.css overwrites custom fillColor

### ISSUE THREAD

**Issue by lsblsb** [robcresswell/vue-material-design-icons#92]
I use Nuxt.js and i am importing your package within a plugin like that:

```
import Vue from 'vue'
import 'vue-material-design-icons/styles.css'
import mdiContentSave from 'vue-material-design-icons/ContentSave.vue'

Vue.component('mdiContentSave', mdiContentSave)
```

When i set the fillColor property of an icon, it is overwritten by the css definition `fill: currentColor` within `.material-design-icon > .material-design-icon__svg`.

The local SVG color is definitly set.

I also tried to import the style as global css file via `nuxt.config.js`. Did not help.

I could just overwrite the CSS property separately, but i want to do it the right way.

Can you help me?

**Comment by robcresswell** [comment]
Hey @lsblsb, thanks for raising an issue! I'd recommend using styling via JS *OR* CSS but *not* both. See the note in https://github.com/robcresswell/vue-material-design-icons#props under `fillcolor`

**Comment by lsblsb** [comment]
Hi @robcresswell, thanks for your reply. I overlooked that relevant piece of informationen. Sorry for that. But one additional answer: In the CSS file and also in that note `fill` is set to `currentColor`. Is `currentColor` only a placeholder for some valid css-color-string ?

**Comment by robcresswell** [comment]
You can read about it here: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentcolor_keyword

**Comment by lsblsb** [comment]
Thats new to me! Great! Thank you for this additional information!

**Comment by robcresswell** [comment]
@lsblsb No problem! Thanks for raising the questions. If anything comes up in future, please feel free to ask.
